using Microsoft.EntityFrameworkCore;
using System;
namespace dotnetShop.Models
{
    public class AppDbContext :DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) 
: base(options)
        {
        }

        public DbSet<Candy> Candies { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<ShoppingCartItem> ShoppingCartItems { get; set; }
      
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Category>().HasData(new Category { CategoryId = 1, CategoryName = "Licorice", CategoryDescription = "Best of Denmark" });
            modelBuilder.Entity<Category>().HasData(new Category { CategoryId = 2, CategoryName = "Chocolates", CategoryDescription = "Blocks of Happiness" });
            modelBuilder.Entity<Category>().HasData(new Category { CategoryId = 3, CategoryName = "Fruit Candy", CategoryDescription = "Like real fruit, just without nutrition value" });
            modelBuilder.Entity<Category>().HasData(new Category { CategoryId = 4, CategoryName = "Vanilla Candy", CategoryDescription = "Very plain" });
           
           
            modelBuilder.Entity<Candy>().HasData(new Candy { CandyId = 13, Name = "Vanilla sth", Price = 2.43M, Description = "Icing bonbon sesame snaps ice cream oat cake. Soufflé gummies cookie oat cake. Sweet jujubes chocolate bar jelly beans.", CategoryId = 4, ImageUrl = "https://images.unsplash.com/photo-1560008581-09826d1de69e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", ImageThumbnailUrl = "https://images.unsplash.com/photo-1560008581-09826d1de69e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", IsInStock = true, IsOnSale = true });
            modelBuilder.Entity<Candy>().HasData(new Candy { CandyId = 1, Name = "Assorted Licorice", Price = 3.5M, Description = "Soufflé croissant chupa chups cupcake brownie sweet roll biscuit cookie topping. Candy canes caramels jelly-o tart cookie. Lollipop apple pie jujubes jelly beans marshmallow chocolate bar chupa chups jelly beans.", CategoryId = 1, ImageUrl = "https://images.unsplash.com/photo-1564424541861-6c68eb0a4309?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1347&q=80", IsInStock = true, IsOnSale = false, ImageThumbnailUrl = "https://images.unsplash.com/photo-1564424541861-6c68eb0a4309?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1347&q=80" });
            modelBuilder.Entity<Candy>().HasData(new Candy { CandyId = 2, Name = "Dark Chocolate", Price = 2.5M, Description = "Ice cream candy fruitcake marzipan wafer carrot cake macaroon. Sugar plum powder lollipop cupcake pastry danish oat cake icing. Icing marzipan pastry caramels gummi bears gingerbread wafer toffee.", CategoryId = 2, ImageUrl = "https://images.unsplash.com/photo-1575377427642-087cf684f29d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60", IsInStock = true, IsOnSale = false, ImageThumbnailUrl = "https://images.unsplash.com/photo-1575377427642-087cf684f29d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60" });
            modelBuilder.Entity<Candy>().HasData(new Candy { CandyId = 3, Name = "Fruit bowl", Price = 4.5M, Description = "Cake chupa chups cheesecake chupa chups donut. Topping chocolate bar danish. Jelly lollipop jelly gummi bears soufflé chocolate cake cake dessert. Bear claw pastry ice cream pastry topping jelly cotton candy fruitcake tart.", CategoryId = 3, ImageUrl = "https://images.unsplash.com/photo-1554908081-267299e53de8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60", IsInStock = true, IsOnSale = false, ImageThumbnailUrl = "https://images.unsplash.com/photo-1554908081-267299e53de8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60" });
            
            modelBuilder.Entity<Candy>().HasData(new Candy { CandyId = 5, Name = "More Licorice", Price = 3.5M, Description = "Soufflé croissant chupa chups cupcake brownie sweet roll biscuit cookie topping. Candy canes caramels jelly-o tart cookie. Lollipop apple pie jujubes jelly beans marshmallow chocolate bar chupa chups jelly beans.", CategoryId = 1, ImageUrl = "https://images.unsplash.com/photo-1564424541861-6c68eb0a4309?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1347&q=80", IsInStock = true, IsOnSale = false, ImageThumbnailUrl = "https://images.unsplash.com/photo-1564424541861-6c68eb0a4309?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1347&q=80" });
            modelBuilder.Entity<Candy>().HasData(new Candy { CandyId = 6, Name = "Light Chocolate", Price = 2.5M, Description = "Ice cream candy fruitcake marzipan wafer carrot cake macaroon. Sugar plum powder lollipop cupcake pastry danish oat cake icing. Icing marzipan pastry caramels gummi bears gingerbread wafer toffee.", CategoryId = 2, ImageUrl = "https://images.unsplash.com/photo-1575377427642-087cf684f29d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60", IsInStock = true, IsOnSale = false, ImageThumbnailUrl = "https://images.unsplash.com/photo-1575377427642-087cf684f29d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60" });
            modelBuilder.Entity<Candy>().HasData(new Candy { CandyId = 7, Name = "Fruit punch", Price = 4.5M, Description = "Cake chupa chups cheesecake chupa chups donut. Topping chocolate bar danish. Jelly lollipop jelly gummi bears soufflé chocolate cake cake dessert. Bear claw pastry ice cream pastry topping jelly cotton candy fruitcake tart.", CategoryId = 3, ImageUrl = "https://images.unsplash.com/photo-1554908081-267299e53de8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60", IsInStock = true, IsOnSale = false, ImageThumbnailUrl = "https://images.unsplash.com/photo-1554908081-267299e53de8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60" });
            modelBuilder.Entity<Candy>().HasData(new Candy { CandyId = 8, Name = "Vanilla lala", Price = 2.43M, Description = "Icing bonbon sesame snaps ice cream oat cake. Soufflé gummies cookie oat cake. Sweet jujubes chocolate bar jelly beans.", CategoryId = 4, ImageUrl = "https://images.unsplash.com/photo-1560008581-09826d1de69e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", ImageThumbnailUrl = "https://images.unsplash.com/photo-1560008581-09826d1de69e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", IsInStock = true, IsOnSale = true }); 
           
            modelBuilder.Entity<Candy>().HasData(new Candy { CandyId = 9, Name = "Salty Licorice", Price = 3.5M, Description = "Soufflé croissant chupa chups cupcake brownie sweet roll biscuit cookie topping. Candy canes caramels jelly-o tart cookie. Lollipop apple pie jujubes jelly beans marshmallow chocolate bar chupa chups jelly beans.", CategoryId = 1, ImageUrl = "https://images.unsplash.com/photo-1564424541861-6c68eb0a4309?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1347&q=80", IsInStock = true, IsOnSale = false, ImageThumbnailUrl = "https://images.unsplash.com/photo-1564424541861-6c68eb0a4309?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1347&q=80" });
            modelBuilder.Entity<Candy>().HasData(new Candy { CandyId = 10, Name = "Nut Chocolate", Price = 2.5M, Description = "Ice cream candy fruitcake marzipan wafer carrot cake macaroon. Sugar plum powder lollipop cupcake pastry danish oat cake icing. Icing marzipan pastry caramels gummi bears gingerbread wafer toffee.", CategoryId = 2, ImageUrl = "https://images.unsplash.com/photo-1575377427642-087cf684f29d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60", IsInStock = true, IsOnSale = false, ImageThumbnailUrl = "https://images.unsplash.com/photo-1575377427642-087cf684f29d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60" });
            modelBuilder.Entity<Candy>().HasData(new Candy { CandyId = 11, Name = "Apple chips", Price = 4.5M, Description = "Cake chupa chups cheesecake chupa chups donut. Topping chocolate bar danish. Jelly lollipop jelly gummi bears soufflé chocolate cake cake dessert. Bear claw pastry ice cream pastry topping jelly cotton candy fruitcake tart.", CategoryId = 3, ImageUrl = "https://images.unsplash.com/photo-1554908081-267299e53de8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60", IsInStock = true, IsOnSale = false, ImageThumbnailUrl = "https://images.unsplash.com/photo-1554908081-267299e53de8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60" });
            modelBuilder.Entity<Candy>().HasData(new Candy { CandyId = 12, Name = "Vanillaaaaa", Price = 2.43M, Description = "Icing bonbon sesame snaps ice cream oat cake. Soufflé gummies cookie oat cake. Sweet jujubes chocolate bar jelly beans.", CategoryId = 4, ImageUrl = "https://images.unsplash.com/photo-1560008581-09826d1de69e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", ImageThumbnailUrl = "https://images.unsplash.com/photo-1560008581-09826d1de69e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", IsInStock = true, IsOnSale = true });
        }
    }
}
